#!/usr/bin/bash
set -e

[ $# -ne 0 ] && {
  echo 'git-xstart: Initializes a new git repository in the current directory'
  echo 'Usage: git xstart';
  exit 1;
}

git init
git commit --allow-empty -m 'Initial commit'
