#!/usr/bin/bash
set -e

[ $# -ne 0 ] && {
  echo 'git-xgraph: Prints a graph showing the relationship between all branches'
  echo 'Usage: git xgraph';
  exit 1;
}

git log \
  --pretty=format:"%C(yellow)%h %cd %C(reset)%s%C(red)%d%C(blue) [%an %ad]" \
  --decorate --simplify-by-decoration --date=short --graph --branches \
  --full-history
